enable noninteractive signing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -151,7 +151,8 @@ jobs:
           echo -e "\`\`\`"   >> ./RELEASE.md
           
           echo "$KEY" > ../cosign.key
-          for FILE in *; do FILE_NAME=$(basename $FILE); cosign sign-blob --key=../cosign.key --output-signature=./${FILE_NAME}.sig ./$FILE_NAME; done
+          for FILE in *; do FILE_NAME=$(basename $FILE); cosign sign-blob --key=../cosign.key --output-signature=./${FILE_NAME}.sig ./$FILE_NAME --yes; done
+          shred -vzn 3 ../cosign.key || echo "WARNING: Failed to shred key file"
           rm -fv ../cosign.key
           ls -a1 "${{env.RELEASE}}"
       # https://github.com/dev-drprasad/delete-tag-and-release, v1
@@ -184,6 +185,8 @@ jobs:
             ${{env.RELEASE}}/index.html.sig
       - name: Cleanup
         run: |
+          shred -vzn 3 ../cosign.key || echo "WARNING: Failed to shred key file"
+          rm -fv ../cosign.key
           cd ${GITHUB_WORKSPACE}
           rm -rfv ./*
       - name: Download current version of the site
